external_components:
  - source: github://tsvane/esphome_components@main
    refresh: 0s
    
nilan:
    
select:
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Set Operation Mode"
    id: nilan_set_operation_mode
    address: 70
    value_type: U_WORD
    optionsmap:
      "Off" : 0
      "Auto" : 1


sensor:

#########################
#### INPUT REGISTERS ####
#########################

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T4 - Outlet"
    id: nilan_outlet_temp_t4
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    value_type: S_WORD
    address: 30
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T2 - Inlet"
    id: nilan_inlet_temp_t2
    unit_of_measurement: °C
    accuracy_decimals: 1
    register_type: read
    value_type: S_WORD
    address: 28
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T1 - Outdoor"
    id: nilan_outdoor_temp_t1
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    value_type: S_WORD
    address: 27
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T3 - Exhaust"
    id: nilan_exhaust_temp_t3
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    value_type: S_WORD
    address: 29
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Humidity"
    id: nilan_humidity
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 31
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Active Alarms"
    id: nilan_active_alarms
    accuracy_decimals: 0
    register_type: read
    address: 50

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm List 1 ID"
    id: nilan_alarm_list_1_id
    accuracy_decimals: 0
    register_type: read
    address: 51

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm List 1 Info"
    id: nilan_alarm_list_1_info
    accuracy_decimals: 0
    register_type: read
    address: 56
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm List 2 ID"
    id: nilan_alarm_list_2_id
    accuracy_decimals: 0
    register_type: read
    address: 52

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm List 2 Info"
    id: nilan_alarm_list_2_info
    accuracy_decimals: 0
    register_type: read
    address: 57

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm List 3 ID"
    id: nilan_alarm_list_3_id
    accuracy_decimals: 0
    register_type: read
    address: 53

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm List 3 Info"
    id: nilan_alarm_list_3_info
    accuracy_decimals: 0
    register_type: read
    address: 58
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Actual Fan Step"
    id: nilan_actual_fan_step
    accuracy_decimals: 0
    register_type: read
    address: 63               

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Days to Next Filter Change"
    id: nilan_days_to_next_filter_alarm
    unit_of_measurement: 'days'
    accuracy_decimals: 0
    register_type: read
    address: 110    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Exhaust Fan Speed"
    id: nilan_exhaust_fan_speed
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 1
    register_type: read
    address: 24
    filters:
      - multiply: 0.1    
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet Fan Speed"
    id: nilan_inlet_fan_speed
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 1
    register_type: read
    address: 25
    filters:
      - multiply: 0.1    
          
###########################
#### HOLDING REGISTERS ####
###########################


binary_sensor:
#########################
#### INPUT REGISTERS ####
#########################

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air Filter Alarm"
    id: nilan_filter_alarm
    register_type: read
    address: 49
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Summer Mode"
    id: nilan_is_summer
    register_type: read
    address: 72
    bitmask: 0

###########################
#### HOLDING REGISTERS ####
###########################


text_sensor:
  
  - platform: template
    name: "Air Filter Alarm Status"
    lambda: |-
      if (id(nilan_filter_alarm).state) {
        return {"Skift Filter"};
      } else {
        return {"Filter OK"};
      }  
number:
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Ventilation Speed"
    id: nilan_ventilation_speed_set
    min_value: 1
    max_value: 4
    step: 1.0
    address: 69 

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Temperature"
    id: nilan_target_temperature_set
    min_value: 10
    max_value: 30
    step: 1.0
    address: 37
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User Function 1 Ventilation Speed"
    id: nilan_userfct1_ventilation_speed_set
    min_value: 0.0
    max_value: 4.0
    step: 1.0
    address: 79 
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User Function 2 Ventilation Speed"
    id: nilan_userfct2_ventilation_speed_set
    min_value: 0.0
    max_value: 4.0
    step: 1.0
    address: 85
 
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User Function 1 Time Set (Minutes)"
    id: nilan_userfct1_time_set
    value_type: U_WORD
    min_value: 1.0
    max_value: 180.0
    step: 1.0
    address: 71

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User Function 2 Time Set (Minutes)"
    id: nilan_userfct2_time_set
    value_type: U_WORD
    min_value: 1.0
    max_value: 180.0
    step: 1.0
    address: 84     

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air Level 1"
    id: nilan_supply_level1
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 59
    multiply: 10   
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air Level 2"
    id: nilan_supply_level2
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 60
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air Level 3"
    id: nilan_supply_level3
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 61
    multiply: 10 
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air Level 4"
    id: nilan_supply_level4
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 62
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air Level 1"
    id: nilan_extract_level1
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 63
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air Level 2"
    id: nilan_extract_level2
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 64
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air Level 3"
    id: nilan_extract_level3
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 65
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air Level 4"
    id: nilan_extract_level4
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 66
    multiply: 10
    
switch:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Reset Filter Timer"
    id: nilan_filter_reset
    register_type: holding
    bitmask: 1
    address: 51
 
  - platform: gpio
    pin: ${user_function_1_output}
    name: "Brugervalg 1"   
    id: nilan_user_function2_switch
      
  - platform: gpio
    pin: ${user_function_2_output}
    name: "Brugervalg 2"   
    id: nilan_user_funtion2_switch      
    
climate:
  - platform: nilan
    name: Nilan
    current_temp_sensor_id: nilan_inlet_temp_t2
    target_temp_sensor_id: nilan_target_temperature_set
    fan_speed_sensor_id: nilan_ventilation_speed_set
    mode_select_id: nilan_set_operation_mode